language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
#    - shellcheck
    - whois
    - gawk
    - mawk
    - original-awk
    - mksh
    - posh
    - dash
    - bash

before_install:
  - sudo apt-get update
  - sudo apt-get install shellcheck

env:
  - AWK=awk
  - AWK=mawk
  - AWK=gawk
  - AWK=original-awk
  - SH=sh
  - SH=mksh
  - SH=posh
  - SH=dash
  - SH=bash

script:
  - shellcheck
  - ./test.sh

# vim:ts=2:sw=2:et
